config = {'datapath':'/home/ysw/EGFR/raw_scans/',
          'preprocess_result_path':'/home/ysw/EGFR/egfr_prep_result/',
          'outputfile':'prediction.csv', 
          'detector_model':'net_detector',
         'detector_param':'./model/detector.ckpt',
         'classifier_model':'net_classifier',
         'classifier_param':'./model/classifier_py3.ckpt',
         'n_gpu':3,
         'n_worker_preprocessing':None,
         'use_exsiting_preprocessing':False,
         'skip_preprocessing':False,
         'skip_detect':True,
         'is_EGFR':True}
