config = {'datapath':'/home/ysw/tmp/stage1',
          'preprocess_result_path':'/home/ysw/ct_data/DSB3/dsb_stage1_prep_result',
          'outputfile':'dsb_stage1_prediction_new.csv', 
          'detector_model':'net_detector',
         'detector_param':'./model/detector.ckpt',
         'classifier_model':'net_classifier',
         'classifier_param':'./model/170.ckpt',
         'n_gpu':64,
         'n_worker_preprocessing':80,
         'use_exsiting_preprocessing':True,
         'skip_preprocessing':True,
         'skip_detect':False,
         'is_EGFR':False}
